manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      # Pin the platform to the Zephyr revision currently validated by RetroPLC.
      revision: da0718ca0d52d4f3e3653ead4f8d3a907778ae0b
      import: true

  self:
    path: retroplc-runtime
